# Project configuration
project_name: "path-integration-rnn"
model_type: "hypergraph"
device: "cuda"
seed: 0 # Global seed


# Data configuration  
num_trajectories: 2000
trajectory_type: 'ornstein_uhlenbeck'
batch_size: 128
num_workers: 7
train_val_split: 0.8


# Trajectory configuration
trajectory_duration: 20 # 20 seconds
num_time_steps: 200 # dt = 0.1s (reasonable neural dynamics timescale)
mu_speed: 0.2
sigma_speed: 0.5
tau_vel: 1

# Place cell configuration
arena_size: 2.2
num_place_cells: 512
place_cell_rf: 0.12
surround_scale: 2
DoG: true


# Model configuration
input_size: 2
output_size: 2
activation: "Tanh"

# Hypergraph-specific configuration
num_nodes: 4096
num_hyperedges: 1000
hypergraph_structure: "random"
max_hyperedge_size: 3
alpha_node: 0.5
alpha_hyperedge: 0.2

# Training configuration
learning_rate: 0.01
weight_decay: 0.0
step_size: 100
gamma: 0.5
max_epochs: 500

#Callback configs
decode_k: 3
log_every_n_epochs: 10

# Training configuration
learning_rate: 0.01
max_epochs: 500