# Project configuration
project_name: "path-integration-rnn"
device: "cuda"  # or "cpu" or "mps" depending on your setup

# Data configuration  
num_trajectories: 2000
batch_size: 128
num_workers: 7
train_val_split: 0.8
start_time: 0
end_time: 100
num_time_steps: 1000
arena_L: 5
mu_speed: 0.2
sigma_speed: 0.5
tau_vel: 1

# Model configuration
input_size: 2
hidden_size: 400
output_size: 2
alpha: 0.7
activation: "ReLU"  # PyTorch activation function name

# Training configuration
learning_rate: 0.01
max_epochs: 500
